name: Discord Bot

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */5 * * *"   # her 5 saatte bir çalıştır (6 saatten kısa olmalı)

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run bot
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
        run: |
          python main.py
